"""Response formatters for Telegram messages.

All functions return formatted text strings ready for tg_send_message.
"""

from __future__ import annotations

from typing import Any

# Circled digit mapping for task numbering
CIRCLED_DIGITS = {
    1: "①", 2: "②", 3: "③", 4: "④", 5: "⑤",
    6: "⑥", 7: "⑦", 8: "⑧", 9: "⑨", 10: "⑩",
    11: "⑪", 12: "⑫", 13: "⑬", 14: "⑭", 15: "⑮",
}


def _circled(n: int) -> str:
    return CIRCLED_DIGITS.get(n, f"({n})")


def _get_val(field: Any) -> str:
    if isinstance(field, dict):
        return field.get("value", "")
    return str(field) if field else ""


def _get_link(field: Any) -> str:
    if isinstance(field, list) and field:
        return ", ".join(
            item.get("value", str(item)) if isinstance(item, dict) else str(item)
            for item in field
        )
    if isinstance(field, dict):
        return field.get("value", str(field))
    return str(field) if field else ""


def format_briefing(briefing_text: str) -> str:
    """Wrap briefing text (already generated by scheduler) for sending."""
    return briefing_text


def format_task_draft(tasks: list[dict], shifts_info: list[dict] | None = None) -> str:
    """Format parsed tasks as a draft for owner confirmation.

    tasks = [{title, task_type, assignee_fio, assignee_hint, priority, ...}]
    shifts_info = [{employee, shift_type, active_tasks}]
    """
    if not tasks:
        return "Задач не обнаружено."

    # Group by type
    groups: dict[str, list[tuple[int, dict]]] = {}
    type_labels = {
        "delegate": "ДЕЛЕГИРОВАНИЕ",
        "collab": "СОВМЕСТНАЯ РАБОТА (ты + бот)",
        "inform": "ИНФОРМИРОВАНИЕ",
        "boss_control": "НА КОНТРОЛЕ У РУКОВОДСТВА",
        "report_up": "ДОКЛАД РУКОВОДСТВУ",
        "regulatory": "РЕГУЛЯТОРНЫЕ",
        "skill_update": "ПРАВКИ СКИЛЛОВ",
        "personal": "ЛИЧНЫЕ",
        "backlog": "БЭКЛОГ",
    }

    for i, t in enumerate(tasks, 1):
        ttype = t.get("task_type", "delegate")
        groups.setdefault(ttype, []).append((i, t))

    lines = [f"Разобрал {len(tasks)} задач:\n"]

    # Build shift lookup for quick info
    shift_lookup: dict[str, dict] = {}
    if shifts_info:
        for s in shifts_info:
            emp = s.get("employee", "")
            shift_lookup[str(emp)] = s

    # Questions to ask
    questions = []

    for ttype in ["delegate", "collab", "inform", "boss_control", "report_up",
                   "regulatory", "skill_update", "personal", "backlog"]:
        items = groups.get(ttype, [])
        if not items:
            continue

        label = type_labels.get(ttype, ttype.upper())
        lines.append(f"{label}:")

        for num, task in items:
            title = task.get("title", "?")
            assignee = task.get("assignee_fio", task.get("assignee_hint", ""))
            deadline = task.get("deadline", "")

            # Build line
            parts = [f"{_circled(num)} {title}"]
            if assignee:
                parts.append(f"→ {assignee}")
            if deadline:
                parts.append(f"до {deadline}")

            # Missing info markers
            missing = []
            if ttype == "delegate" and not assignee:
                missing.append("кому?")
            if not deadline and ttype not in ("backlog", "skill_update"):
                missing.append("срок?")
            if ttype == "delegate" and not task.get("delivery_method"):
                missing.append("через что ставим?")

            if missing:
                parts.append(" | ".join(missing))

            lines.append("  " + " | ".join(parts))

            # Shift/load info for assignee
            if assignee and assignee in shift_lookup:
                si = shift_lookup[assignee]
                stype = si.get("shift_type", "")
                active = si.get("active_tasks", 0)
                schedule = si.get("schedule_type", "")
                if stype:
                    lines.append(f"    ⚡ {assignee} — {stype}, задач: {active}")
                elif schedule:
                    lines.append(f"    📅 {assignee} — {schedule}, задач: {active}")

            # Collect questions
            if missing:
                questions.append((num, missing))

        lines.append("")

    # Questions summary
    if questions:
        lines.append("Уточни:")
        for num, missing in questions:
            lines.append(f"- {_circled(num)}: {', '.join(missing)}")

    return "\n".join(lines).strip()


def format_task_list(tasks: list[dict], title: str = "Задачи") -> str:
    """Format a list of tasks with statuses."""
    if not tasks:
        return f"{title}: пусто."

    status_icons = {
        "draft": "📝",
        "assigned": "📋",
        "in_progress": "🔄",
        "done": "✅",
        "overdue": "🔴",
        "cancelled": "❌",
        "handed_over": "🔁",
        "waiting_input": "⏳",
    }

    lines = [f"{title} ({len(tasks)}):", ""]
    for i, t in enumerate(tasks, 1):
        status = _get_val(t.get("status", ""))
        icon = status_icons.get(status, "•")
        title_text = t.get("title", "?")
        assignee = _get_link(t.get("assignee", ""))
        deadline = t.get("deadline", "")

        line = f"{icon} {title_text}"
        if assignee:
            line += f" | {assignee}"
        if deadline:
            line += f" | до {str(deadline)[:10]}"
        lines.append(line)

    return "\n".join(lines)


def format_handover(handover_text: str) -> str:
    """Wrap handover push text."""
    return handover_text


def format_anomaly_alert(anomalies: list[dict]) -> str:
    """Format anomaly alerts."""
    if not anomalies:
        return ""

    lines = ["⚠️ АНОМАЛИИ:", ""]
    for a in anomalies:
        atype = a.get("type", "")
        emp = a.get("employee", a.get("task", ""))
        detail = a.get("detail", "")

        type_labels = {
            "overload": "Перегруз",
            "idle": "Простой",
            "chronic_overdue": "Хронические просрочки",
            "performance_drop": "Падение показателей",
            "shift_imbalance": "Дисбаланс смен",
            "stale_task": "Зависшая задача",
        }
        label = type_labels.get(atype, atype)
        lines.append(f"• {label}: {emp} — {detail}")

    lines.append("")
    lines.append("Обратить внимание?")
    return "\n".join(lines)


def format_weekly_report_summary(summary: dict) -> str:
    """Format weekly report summary (text version)."""
    total = summary.get("total", 0)
    completed = summary.get("completed", 0)
    overdue = summary.get("overdue", 0)
    in_progress = summary.get("in_progress", 0)

    lines = [
        f"📊 ЕЖЕНЕДЕЛЬНЫЙ ОТЧЁТ ({summary.get('period_start', '')} — {summary.get('period_end', '')})",
        "",
        "ОБЩАЯ СТАТИСТИКА:",
        f"- Поставлено: {total} | Выполнено: {completed} | Просрочено: {overdue} | В работе: {in_progress}",
        "",
    ]

    employees = summary.get("employees", [])
    if employees:
        lines.append("ИСПОЛНИТЕЛИ:")
        for i, emp in enumerate(employees, 1):
            fio = emp.get("fio", "?")
            t = emp.get("tasks_total", 0)
            rate = f"{emp.get('on_time_rate', 0):.0%}"
            marker = "✅" if emp.get("on_time_rate", 0) >= 0.9 else ("🔴" if emp.get("overdue_rate", 0) > 0.3 else "")
            lines.append(f"{i}. {fio} — {t} задач, {rate} в срок {marker}")

    return "\n".join(lines)


def format_weekend_plan(plan_text: str) -> str:
    """Wrap weekend plan text."""
    return plan_text
